# Generated by Django 4.2.6 on 2023-10-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True, null=True, verbose_name='file_name')),
                ('audiofile', models.FileField(blank=True, default=None, upload_to='audiofile/')),
                ('mood_detected', models.TextField(blank=True, choices=[['Happy', 'Happy'], ['Sad', 'Sad'], ['Calm', 'Calm']], null=True)),
                ('mood_verified', models.TextField(blank=True, choices=[['Happy', 'Happy'], ['Sad', 'Sad'], ['Calm', 'Calm']], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
    ]
