# Generated by Django 4.2.6 on 2023-10-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audiofile_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='mood_verified',
        ),
    ]
